routes/web.php
<?php

use App\Http\Controllers\CandidateController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ElectionController;
use App\Http\Controllers\PartyListController;
use App\Http\Controllers\VoterController;
use App\Http\Controllers\VoteSubmitController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::group(['middleware' => ['canVote']], function () {

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard')->middleware(['auth']);

    Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function () {
        Route::resource('voter', VoterController::class);
        Route::resource('election', ElectionController::class);
        Route::resource('candidate', CandidateController::class);
        Route::resource('partylist', PartyListController::class);
    });
    Route::group(['prefix' => 'student', 'middleware' => ['role:student']], function () {
        Route::post('submitvote', [VoteSubmitController::class, 'store'])->name('submitvote.store');
    });
});




require __DIR__ . '/auth.php';

app/Models/PartyList.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PartyList extends Model
{
    use HasFactory;
    protected $fillable = ['name'];
}

app/Http/Controllers/PartyListController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PartyListRequest;
use App\Models\PartyList;
use Illuminate\Http\Request;

class PartyListController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('users.admin.partylist.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.admin.partylist.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PartyListRequest $request)
    {
        PartyList::create($request->validated());
        return redirect()->route('partylist.index')->with('message', 'Party List Added successfully');
    }



    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\PartyList  $partyList
     * @return \Illuminate\Http\Response
     */
    public function edit(PartyList $partylist)
    {
        return view('users.admin.partylist.edit', compact('partylist'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\PartyList  $partyList
     * @return \Illuminate\Http\Response
     */
    public function update(PartyListRequest $request, PartyList $partylist)
    {
        $partylist->update($request->validated());
        return redirect()->route('partylist.index')->with('message', 'Party List Updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\PartyList  $partyList
     * @return \Illuminate\Http\Response
     */
    public function destroy(PartyList $partylist)
    {
        $partylist->delete();
        return redirect()->route('partylist.index')->with('message', 'Party List Succesfully Removed');
    }
}

app/Http/Livewire/PartyListTable.php
<?php

namespace App\Http\Livewire;

use App\Models\PartyList;
use Livewire\Component;

class PartyListTable extends Component
{
    public function render()
    {

        return view(
            'livewire.party-list-table',
            [
                'partylists' => PartyList::all()
            ]
        );
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/users/admin/partylist/create.blade.php
<x-app-layout>
    <x-slot name="header">
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">
        {{ __('Create New Party List') }}
      </h2>
    </x-slot>

    <div class="py-12">
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
          <div class="p-6 bg-white border-b border-gray-200">


            <x-auth-validation-errors />
            <form method="POST" action="{{ route('partylist.store') }}">
              @csrf
              <div class="grid grid-cols-1 gap-6 mt-5">

                  <div>
                      <x-label for="name" :value="__('Party List Name')" />
                      <x-input id="name" class="block mt-1 w-full" type="text" name="name"
                        :value="old('name')" />
                    </div>

              </div>

                <div class="flex items-center justify-end mt-4">
                  <x-back-button href="{{ route('election.index') }}"  class="ml-3">
                      {{ __('Back') }}
                  </x-back-button>
                <x-button class="ml-3">
                  {{ __('Create') }}
                </x-button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </x-app-layout>

resources/views/users/admin/partylist/edit.blade.php
<x-app-layout>
    <x-slot name="header">
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">
        {{ __('Update Party List Information') }}
      </h2>
    </x-slot>

    <div class="py-12">
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
          <div class="p-6 bg-white border-b border-gray-200">


            <x-auth-validation-errors />
            <form method="POST" action="{{ route('partylist.update', $partylist ) }}" >
              @method('PUT')
              @csrf
              <div class="grid grid-cols-1 gap-6">

                <div>
                    <x-label for="name" :value="__('Party List Name')" />
                    <x-input id="name" class="block mt-1 w-full" type="text" name="name"

                      value="{{ $partylist->name }}" autofocus />

                </div>

              </div>
              <div class="flex items-center justify-end mt-4">
                <x-button class="ml-3">
                  {{ __('Create') }}
                </x-button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </x-app-layout>

resources/views/users/admin/partylist/index.blade.php
<x-app-layout>
    <x-slot name="header">
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">
        {{ __('Party List') }}
      </h2>
    </x-slot>

    <div class="py-12">
      <div class="max-w-8xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-x-auto shadow-sm sm:rounded-lg">
          <div class="relative flex space-x-4  my-6 mx-6">
            <a href="{{ route('partylist.create') }}"
              class="bg-purple-400 hover:bg-purple-600 text-white py-2 px-4 rounded">Add
              Party List</a>
            <x-input wire:model.debounce.300ms="search" id="search" class="absolute right-0 w-1/3" type="search"
              name="search" placeholder="Search Party List" :value="old('search')" />
          </div>


          <div class="p-6 bg-white border-b border-gray-200">
            <div x-data="{ show: true }" x-show.transition.opacity.out.duration.2000ms="show"
              x-init="setTimeout(() => show = false, 3000)">
              <x-success-message />
            </div>

            <!-- component -->
            @livewire('party-list-table')
          </div>
        </div>
      </div>
    </div>
  </x-app-layout>