routes/web.php
<?php

use App\Http\Controllers\CandidateController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ElectionController;
use App\Http\Controllers\PartyListController;
use App\Http\Controllers\VoterController;
use App\Http\Controllers\VoteSubmitController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::group(['middleware' => ['canVote']], function () {

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard')->middleware(['auth']);

    Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function () {
        Route::resource('voter', VoterController::class);
        Route::resource('election', ElectionController::class);
        Route::resource('candidate', CandidateController::class);
        Route::resource('partylist', PartyListController::class);
    });
    Route::group(['prefix' => 'student', 'middleware' => ['role:student']], function () {
        Route::post('submitvote', [VoteSubmitController::class, 'store'])->name('submitvote.store');
    });
});




require __DIR__ . '/auth.php';

app/Http/Controllers/VoterController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\VoterRequest;
use App\Models\Course;
use App\Models\User;
use Illuminate\Support\Facades\File;

class VoterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('users.admin.voters.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $courses = Course::get();
        return view('users.admin.voters.create', compact('courses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(VoterRequest $request)
    {


        $voter = User::create($request->validated());
        $voter->attachRole('student');

        if ($request->hasFile('avatar')) {
            $avatar =  $voter->id . '-' . $request->first_name . '-' . $request->last_name . '.' . $request->avatar->getClientOriginalExtension();
            $request->avatar->move(public_path('images/profile'), $avatar);
            $voter->update(['avatar' => $avatar]);
        }

        return redirect()->route('voter.index')->with('message', 'Voter Added successfully');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $voter)
    {
        $courses = Course::get();
        return view('users.admin.voters.edit', compact('voter', 'courses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(VoterRequest $request, User $voter)
    {

        unlink("images/profile/" . $voter->avatar);
        $voter->update($request->validated());
        if ($request->hasFile('avatar')) {
            $avatar =  $voter->id . '-' . $request->first_name . '-' . $request->last_name . '.' . $request->avatar->getClientOriginalExtension();
            $request->avatar->move(public_path('images/profile'), $avatar);
            $voter->update(['avatar' => $avatar]);
        }
        return redirect()->route('voter.index')->with('message', 'Teacher Profile Updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $voter)
    {
        $voter->delete();
        File::delete('images/profile/' . $voter->avatar);
        return redirect()->route('voter.index')->with('message', 'Teacher Profile Deleted successfully');
    }
}

app/Http/Livewire/VoterTable.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;

class VoterTable extends Component
{
    public function render()
    {
        $voters = User::with('course')->whereRoleIs('student')->get();
        return view('livewire.voter-table', compact('voters'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/users/admin/voters/create.blade.php
<x-app-layout>
  <x-slot name="header">
    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
      {{ __('Create New Voter') }}
    </h2>
  </x-slot>

  <div class="py-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
      <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
        <div class="p-6 bg-white border-b border-gray-200">


          <x-auth-validation-errors />
          <form method="POST" action="{{ route('voter.store') }}" enctype="multipart/form-data">
            @csrf
            <div class="grid grid-cols-3 gap-6">

              <div>
                <x-label for="name" :value="__('First Name')" />
                <x-input id="first_name" class="block mt-1 w-full" type="text" name="first_name"
                  :value="old('first_name')" autofocus />
              </div>

              <div>
                <x-label for="middle_name" :value="__('Middle Name')" />
                <x-input id="middle_name" class="block mt-1 w-full" type="text" name="middle_name"
                  :value="old('middle_name')" />
              </div>

              <div>
                <x-label for="last_name" :value="__('Last Name')" />
                <x-input id="last_name" class="block mt-1 w-full" type="text" name="last_name"
                  :value="old('last_name')" />
              </div>

              <div>
                <x-label for="gender" :value="__('Gender')" />
                <select id="gender" name="gender" :value="old('gender')"
                  class="block mt-1 w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">


                  <option value="Male">Male</option>
                  <option value="Female">Female</option>
                  <option value="Others">Others</option>

                </select>
              </div>

              <div>
                <x-label for="section" :value="__('Section')" />
                <x-input id="section" class="block mt-1 w-full" type="text" name="section" :value="old('section')" />
              </div>

              <div>
                <x-label for="year_level" :value="__('Year Level')" />
                <select id="year_level" name="year_level" :value="old('year_level')"
                  class="block mt-1 w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
                  <option value="First Year">First Year</option>
                  <option value="Second Year">Second Year</option>
                  <option value="Third Year">Third Year</option>
                  <option value="Fourth Yea">Fourth Year</option>
                </select>
              </div>

              <div>
                <x-label for="course_id" :value="__('Course')" />
                <select id="course_id" name="course_id" :value="old('course_id')"
                  class="block mt-1 w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">


                  @foreach ($courses as $course)
                  <option value="{{$course->id }}">{{ $course->description }}</option>
                  @endforeach

                </select>
              </div>

              <div>
                <x-label for="email" :value="__('Email')" />
                <x-input id="email" class="block mt-1 w-full" type="email" name="email" :value="old('email')" />
              </div>

              <div>
                <x-label for="avatar" :value="__('Image')" />
                <x-input id="avatar" class="block mt-1 w-full" type="file" name="avatar" :value="old('avatar')" />
              </div>

            </div>
            <div class="flex items-center justify-end mt-4">
              <x-button class="ml-3">
                {{ __('Create') }}
              </x-button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</x-app-layout>

resources/views/users/admin/voters/edit.blade.php
<x-app-layout>
  <x-slot name="header">
    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
      {{ __('Update Voter Information') }}
    </h2>
  </x-slot>

  <div class="py-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
      <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
        <div class="p-6 bg-white border-b border-gray-200">


          <x-auth-validation-errors />
          <form method="POST" action="{{ route('voter.update', $voter ) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="grid grid-cols-3 gap-6">

              <div>
                <x-label for="name" :value="__('First Name')" />
                <x-input id="first_name" class="block mt-1 w-full" type="text" name="first_name"
                  value="{{ $voter->first_name }}" autofocus />

              </div>

              <div>
                <x-label for="middle_name" :value="__('Middle Name')" />
                <x-input id="middle_name" class="block mt-1 w-full" type="text" name="middle_name"
                  value="{{ $voter->middle_name }}" />
              </div>

              <div>
                <x-label for="last_name" :value="__('Last Name')" />
                <x-input id="last_name" class="block mt-1 w-full" type="text" name="last_name"
                  value="{{ $voter->last_name }}" />
              </div>

              <div>
                <x-label for="gender" :value="__('Gender')" />
                <select id="gender" name="gender" :value="old('gender')"
                  class="block mt-1 w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
                  <option value="Male" @if ($voter->gender === "Male" ) selected @endif>Male</option>
                  <option value="Female" @if ($voter->gender === "Female" ) selected @endif>Female</option>
                  <option value="Other" @if ($voter->gender === "Others" ) selected @endif>Other</option>
                </select>
              </div>

              <div>
                <x-label for="section" :value="__('Section')" />
                <x-input id="section" class="block mt-1 w-full" type="text" name="section"  value="{{ $voter->section }}" />
              </div>

              <div>
                <x-label for="year_level" :value="__('Year Level')" />
                <select id="year_level" name="year_level" :value="old('year_level')"
                  class="block mt-1 w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">

                  <option value="First Year" @if ($voter->year_level === "First Year" ) selected @endif>First Year</option>
                  <option value="Second Year" @if ($voter->year_level === "Second Year" ) selected @endif>Second Year</option>
                  <option value="Third Year"  @if ($voter->year_level === "Third Year" ) selected @endif>Third Year</option>
                  <option value="Fourth Year" @if ($voter->year_level === "Fourth Year" ) selected @endif>Fourth Year</option>
                </select>
              </div>

              <div>
                <x-label for="course_id" :value="__('Course')" />
                <select id="course_id" name="course_id" :value="old('course_id')"
                  class="block mt-1 w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">


                  @foreach ($courses as $course)
                  <option value="{{$course->id }}">{{ $course->description }}</option>
                  @endforeach

                </select>
              </div>

              <div>
                <x-label for="email" :value="__('Email')" />
                <x-input id="email" class="block mt-1 w-full" type="email" name="email" value="{{ $voter->email }}" />

              </div>

              <div>
                <x-label for="avatar" :value="__('Image')" />
                <div class="flex">
                  @if (!$voter->avatar)
                  <img src="{{ Avatar::create($voter->first_name . ' ' . $voter->last_name)->toBase64() }}"
                    class="mx-2" />
                  @else
                  <img src="{{asset('images/profile/'. $voter->avatar)}}" alt="Teacher Picture"
                    class="w-12 h-12 border dark:border-coolGray-700">
                  @endif
                  <x-input id="avatar" class="block ml-3 mt-1 w-full" type="file" name="avatar"
                    :value="old('avatar')" />
                </div>

              </div>

            </div>
            <div class="flex items-center justify-end mt-4">
              <x-button class="ml-3">
                {{ __('Update') }}
              </x-button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</x-app-layout>

resources/views/users/admin/voters/index.blade.php
<x-app-layout>
  <x-slot name="header">
    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
      {{ __('Voters') }}
    </h2>
  </x-slot>

  <div class="py-12">
    <div class="max-w-8xl mx-auto sm:px-6 lg:px-8">
      <div class="bg-white overflow-x-auto shadow-sm sm:rounded-lg">
        <div class="relative flex space-x-4  my-6 mx-6">
          <a href="{{ route('voter.create') }}"
            class="bg-purple-400 hover:bg-purple-600 text-white py-2 px-4 rounded">Add
            Voters</a>
          <x-input wire:model.debounce.300ms="search" id="search" class="absolute right-0 w-1/3" type="search"
            name="search" placeholder="Search Voter" :value="old('search')" />
        </div>


        <div class="p-6 bg-white border-b border-gray-200">
          <div x-data="{ show: true }" x-show.transition.opacity.out.duration.2000ms="show"
            x-init="setTimeout(() => show = false, 3000)">
            <x-success-message />
          </div>

          <!-- component -->
          @livewire('voter-table')
        </div>
      </div>
    </div>
  </div>
</x-app-layout>