routes/web.php
<?php

use App\Http\Controllers\CandidateController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ElectionController;
use App\Http\Controllers\PartyListController;
use App\Http\Controllers\VoterController;
use App\Http\Controllers\VoteSubmitController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::group(['middleware' => ['canVote']], function () {

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard')->middleware(['auth']);

    Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function () {
        Route::resource('voter', VoterController::class);
        Route::resource('election', ElectionController::class);
        Route::resource('candidate', CandidateController::class);
        Route::resource('partylist', PartyListController::class);
    });
    Route::group(['prefix' => 'student', 'middleware' => ['role:student']], function () {
        Route::post('submitvote', [VoteSubmitController::class, 'store'])->name('submitvote.store');
    });
});




require __DIR__ . '/auth.php';

app/Http/Livewire/CandidatePosition.php
<?php

namespace App\Http\Livewire;

use App\Models\Election;
use App\Models\Postions;
use Livewire\Component;

class CandidatePosition extends Component
{

    public $selectedElection = null;
    public $selectedPosition = null;
    public $positions = [];

    public function render()
    {
        return view(
            'livewire.candidate-position',
            [
                'elections' => Election::where('status', 0)->get()
            ],
        );
    }

    public function updatedSelectedElection($elections_id)
    {
        $this->positions = Postions::where('election_id', $elections_id)->get();
    }
}

app/Http/Livewire/CandidateSearch.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;

class CandidateSearch extends Component
{

    public $query;
    public $candidate = [];

    public function mount()
    {
        $this->query = '';
        $this->candidate = '';
    }

    public function updatedQuery()
    {
        $this->candidate = User::with('course')->where('id',  $this->query)
            ->first();
    }

    public function render()
    {
        info($this->candidate);
        return view('livewire.candidate-search');
    }
}

app/Http/Livewire/CandidateTable.php
<?php

namespace App\Http\Livewire;

use App\Models\Candidate;
use Livewire\Component;

class CandidateTable extends Component
{
    public function render()
    {
        $candidates = Candidate::with('election', 'position', 'candidateInfo')->get();
        return view('livewire.candidate-table', compact('candidates'));
    }
}

app/Http/Livewire/EditPosition.php
<?php

namespace App\Http\Livewire;

use App\Models\Election;
use App\Models\Postions;
use Livewire\Component;

class EditPosition extends Component
{
    public $positions = [];

    public function mount(Election $election)
    {

        $postions = Postions::with('election')->where('election_id', $election->id)->get();

        foreach ($postions as $position) {
            $this->positions[] =
                [
                    'id' => $position->id,
                    'position' => $position->positions
                ];
        }
    }

    /**
     * Write code on Method
     *
     * @return response()
     */
    public function addPosition()
    {
        $this->positions[] = ['position' => ''];
    }
    /**
     * Write code on Method
     *
     * @return response()
     */
    public function removePosition($index)
    {
        unset($this->positions[$index]);
        $this->positions = array_values($this->positions);
    }

    public function render()
    {
        info($this->positions);
        return view('livewire.edit-position');
    }
}

app/Http/Livewire/ElectionTable.php
<?php

namespace App\Http\Livewire;

use App\Models\Election;
use Livewire\Component;

class ElectionTable extends Component
{

    public function render()
    {
        $elections = Election::orderBy('id', 'desc')->get();
        return view('livewire.election-table', compact('elections'));
    }
}

app/Http/Livewire/PartyListTable.php
<?php

namespace App\Http\Livewire;

use App\Models\PartyList;
use Livewire\Component;

class PartyListTable extends Component
{
    public function render()
    {

        return view(
            'livewire.party-list-table',
            [
                'partylists' => PartyList::all()
            ]
        );
    }
}

app/Http/Livewire/Position.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Position extends Component
{
    public $positions = [];

    public function mount()
    {
        $this->positions = [
            [
                'position' => 'President'

            ],
            [
                'position' => 'Vice-President'
            ],
            [
                'position' => 'Secretary'
            ],
        ];
    }

    /**
     * Write code on Method
     *
     * @return response()
     */
    public function addPosition()
    {
        $this->positions[] = ['position' => ''];
    }
    /**
     * Write code on Method
     *
     * @return response()
     */
    public function removePosition($index)
    {
        unset($this->positions[$index]);
        $this->positions = array_values($this->positions);
    }

    public function render()
    {
        info($this->positions);
        return view('livewire.position');
    }
}

app/Http/Livewire/TypeOfVoter.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\College;
use App\Models\Course;

class TypeOfVoter extends Component
{
    public $whoCanVote = 'All Student';
    public $typeOfVoter;
    public function render()
    {
        $colleges = College::get();
        $courses = Course::get();
        return view('livewire.type-of-voter', compact('colleges', 'courses'));
    }
}

app/Http/Livewire/VoteList.php
<?php

namespace App\Http\Livewire;

use App\Models\Election;
use Livewire\Component;

class VoteList extends Component
{
    public function render()
    {
        $elections = Election::with('position.candidate.candidateInfo', 'position.candidate.partyList', 'position.candidate.voteCount')->where('status', 1)->first();
        // dd($elections);
        return view('livewire.vote-list', compact('elections'));
    }
}

app/Http/Livewire/VoterTable.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;

class VoterTable extends Component
{
    public function render()
    {
        $voters = User::with('course')->whereRoleIs('student')->get();
        return view('livewire.voter-table', compact('voters'));
    }
}

resources/views/livewire/candidate-position.blade.php
<div class="grid grid-cols-2 gap-6 mt-5">

       <div>
        <x-label for="election_id" :value="__('Election Name')" />
        <select id="election_id" name="election_id" :value="old('election_id')"
        class="block mt-1 w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
        wire:model="selectedElection">
            <option value="">Select a Election</option>
                @foreach ($elections as $item)
                    <option value="{{ $item->id }}">{{ $item->name }}</option>
                @endforeach
        </select>

       </div>

        <div>
            <x-label for="position_id" :value="__('Position')" />
        <select id="position_id" name="position_id" :value="old('position_id')"
        class="block mt-1 w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
        wire:model="selectedPosition" >

        <option value="">Select a Position</option>
                @foreach ($positions as $position)
                <option value="{{ $position->id }}">{{ $position->positions }}</option>
                @endforeach
        </select>
        </div>
</div>

resources/views/livewire/candidate-table.blade.php
<div class="overflow-x-auto" >
    <div class="w-full">
        <div class="bg-white shadow-md rounded  border-4  border-opacity-100">
            <table class="min-w-max w-full table-auto">
                <thead>
                    <tr class="bg-gray-200 text-gray-600 uppercase text-md leading-normal">
                        <th class="py-3 px-6 text-left">Position</th>
                        <th class="py-3 px-6 text-left">Candidate Name</th>
                        <th class="py-3 px-6 text-left">Year Level</th>
                        <th class="py-3 px-6 text-left">Gender</th>
                        <th class="py-3 px-6 text-left">Election</th>
                        <th class="py-3 px-6 text-center">Actions</th>
                    </tr>
                </thead>
                <tbody class="text-gray-600 text-base font-light">
                    @foreach ($candidates as $candidate)
                    <tr class="border-b border-gray-200 hover:bg-gray-100">

                        <td class="py-3 px-6 text-left whitespace-nowrap">
                            <div class="flex items-center">
                                <div class="mr-2">
                                    {{ $candidate->position->positions }}
                                </div>
                            </div>
                        </td>


                        <td class="py-3 px-6 text-left whitespace-nowrap">
                            <div class="flex items-center">
                                <div class="mr-2">
                                    @if (!$candidate->candidateInfo->avatar)
                                    <img
                                        src="{{ Avatar::create($candidate->candidateInfo->first_name . ' ' . $candidate->candidateInfo->last_name)->toBase64() }}" />
                                    @else
                                    <img class="w-6 h-6 rounded-full"
                                        src="{{ asset('images/profile/'.$candidate->candidateInfo->avatar) }}" alt="Voter Profile" />
                                    @endif
                                </div>
                                <span>{{ $candidate->candidateInfo->first_name . ' ' .  $candidate->candidateInfo->last_name}}</span>
                                    {{-- {{ $candidate->candidateInfo->first_name . " " . $candidate->candidateInfo->last_name}} --}}

                            </div>
                        </td>

                        <td class="py-3 px-6 text-center whitespace-nowrap">
                            <div class="flex items-right">
                                <div class="mr-2">
                                    {{ $candidate->candidateInfo->year_level }}
                                </div>
                            </div>
                        </td>

                        <td class="py-3 px-6 text-center whitespace-nowrap">
                            <div class="flex items-right">
                                <div class="mr-2">
                                    {{ $candidate->candidateInfo->gender }}
                                </div>
                            </div>
                        </td>

                        <td class="py-3 px-6 text-center whitespace-nowrap">
                            <div class="flex items-right">
                                <div class="mr-2">
                                    {{ $candidate->election->name }}
                                </div>
                            </div>
                        </td>

                        <td class="py-3 px-6 text-center">
                            <div class="flex item-center justify-center">
                                <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                    </svg>
                                </div>
                                <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                    <a href="{{ route('candidate.edit', $candidate) }}">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                        </svg>
                                    </a>
                                </div>
                                <div class="w-4 mr-2 transform hover:text-red-500 hover:scale-110">
                                    <form action="{{ route('candidate.destroy', $candidate) }}" method="POST" >
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" onclick="return confirm('Are you sure?')" class="w-4 h-4">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 1 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                    d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                            </svg>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

resources/views/livewire/election-table.blade.php
<div class="overflow-x-auto" >
    <div class="w-full">
        <div class="bg-white shadow-md rounded  border-4  border-opacity-100">
            <table class="min-w-max w-full table-auto">
                <thead>
                    <tr class="bg-gray-200 text-gray-600 uppercase text-md leading-normal">
                        <th class="py-3 px-6 text-left">Election Name</th>
                        <th class="py-3 px-6 text-center">Status</th>
                        <th class="py-3 px-6 text-center">Type Of Voters</th>
                        {{-- <th class="py-3 px-6 text-center">Start of Election</th>
                        <th class="py-3 px-6 text-center">End of Election</th> --}}
                        <th class="py-3 px-6 text-center">Actions</th>
                    </tr>
                </thead>
                <tbody class="text-gray-600 text-base font-light">
                    @foreach ($elections as $election)
                    <tr class="border-b border-gray-200 hover:bg-gray-100">

                        <td class="py-3 px-6 text-left whitespace-nowrap">
                            <div class="flex items-center">
                                <div class="mr-2">
                                    {{ $election->name }}
                                </div>
                            </div>
                        </td>

                        <td class="py-3 px-6 text-left">
                            <div class="flex items-center justify-center">

                                <div class="flex items-center justify-center w-full2">
                                    @if ($election->status)
                                    <span class="bg-purple-200 text-purple-600 py-1 px-3 rounded-full text-xs">Active</span>
                                    @else
                                    <span class="bg-red-200 text-red-600 py-1 px-3 rounded-full text-xs">Not Active</span>
                                    @endif

                                  </div>
                            </div>
                        </td>

                        <td class="py-3 px-6 text-center">
                            <div class="flex items-center justify-center">
                                {{ $election->typeOfVoters }}
                            </div>

                        </td>

                        {{-- <td class="py-3 px-6 text-center">
                            <div class="flex items-center justify-center">
                                {{ $election->start->toFormatedDate() }}
                            </div>

                        </td>

                        <td class="py-3 px-6 text-center">
                            <div class="flex item-center justify-center">
                                {{ $election->end->toFormatedDate() }}
                            </div>

                        </td> --}}

                        <td class="py-3 px-6 text-center">
                            <div class="flex item-center justify-center">
                                <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                    </svg>
                                </div>
                                <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                    <a href="{{ route('election.edit', $election) }}">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                        </svg>
                                    </a>
                                </div>
                                <div class="w-4 mr-2 transform hover:text-red-500 hover:scale-110">
                                    <form action="{{ route('election.destroy', $election) }}" method="POST" >
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" onclick="return confirm('Are you sure?')" class="w-4 h-4">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 1 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                    d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                            </svg>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

resources/views/livewire/party-list-table.blade.php
<div class="overflow-x-auto" >
    <div class="w-full">
        <div class="bg-white shadow-md rounded  border-4  border-opacity-100">
            <table class="min-w-max w-full table-auto">
                <thead>
                    <tr class="bg-gray-200 text-gray-600 uppercase text-md leading-normal">
                        <th class="py-3 px-6 text-left">Party List</th>
                        <th class="py-3 px-6 text-center">Actions</th>
                    </tr>
                </thead>
                <tbody class="text-gray-600 text-base font-light">
                    @foreach ($partylists as $partylist)
                    <tr class="border-b border-gray-200 hover:bg-gray-100">

                        <td class="py-3 px-6 text-left whitespace-nowrap">
                            <div class="flex items-center">
                                <div class="mr-2">
                                    {{ $partylist->name }}
                                </div>
                            </div>
                        </td>



                        <td class="py-3 px-6 text-center">
                            <div class="flex item-center justify-center">
                                <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                    </svg>
                                </div>
                                <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                    <a href="{{ route('partylist.edit', $partylist) }}">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                        </svg>
                                    </a>
                                </div>
                                <div class="w-4 mr-2 transform hover:text-red-500 hover:scale-110">
                                    <form action="{{ route('partylist.destroy', $partylist) }}" method="POST" >
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" onclick="return confirm('Are you sure?')" class="w-4 h-4">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 1 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                    d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                            </svg>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

resources/views/livewire/voter-table.blade.php
<div class="overflow-x-auto">
    <div class="w-full ">
        <div class="bg-white shadow-md rounded  border-4  border-opacity-100">
            <table class="min-w-max w-full table-auto">
                <thead>
                    <tr class="bg-gray-200 text-gray-600 uppercase text-md leading-normal">
                        <th class="py-3 px-6 text-left">Student ID</th>
                        <th class="py-3 px-6 text-left">Name</th>
                        <th class="py-3 px-6 text-center">Gender</th>
                        <th class="py-3 px-6 text-center">Section</th>
                        <th class="py-3 px-6 text-center">Year Level</th>
                        <th class="py-3 px-6 text-center">Course</th>
                        <th class="py-3 px-6 text-center">Email</th>
                        <th class="py-3 px-6 text-center">Status</th>
                        <th class="py-3 px-6 text-center">Actions</th>
                    </tr>
                </thead>
                <tbody class="text-gray-600 text-base font-light">
                    @foreach ($voters as $voter)


                    <tr class="border-b border-gray-200 hover:bg-gray-100">
                        <td class="py-3 px-6 text-left whitespace-nowrap">
                            <div class="flex items-center">
                                <div class="mr-2">
                                    {{ $voter->id }}
                                </div>
                            </div>
                        </td>
                        <td class="py-3 px-6 text-left">
                            <div class="flex items-center">
                                <div class="mr-2">
                                    @if (!$voter->avatar)
                                    <img
                                        src="{{ Avatar::create($voter->first_name . ' ' . $voter->last_name)->toBase64() }}" />
                                    @else
                                    <img class="w-6 h-6 rounded-full"
                                        src="{{ asset('images/profile/'.$voter->avatar) }}" alt="Voter Profile" />
                                    @endif
                                </div>
                                <span>{{ $voter->first_name . ' ' .  $voter->last_name}}</span>
                            </div>
                        </td>

                        <td class="py-3 px-6 text-center">
                            <div class="flex items-center justify-center">
                                {{ $voter->gender }}
                        </td>

                        <td class="py-3 px-6 text-center">
                            <div class="flex items-center justify-center">
                                {{ $voter->section }}
                        </td>

                        <td class="py-3 px-6 text-center">
                            <div class="flex items-center justify-center">
                                {{ $voter->year_level }}
                        </td>

                        <td class="py-3 px-6 text-center">
                            <div class="flex items-center justify-center">
                                {{ $voter->course->description }}
                        </td>

                        <td class="py-3 px-6 text-center">
                            <div class="flex item-center justify-center">
                                {{ $voter->email}}
                            </div>
                        </td>

                        <td class="py-3 px-6 text-center">
                            @if ($voter->status)
                                <span class=" bg-red-200 text-red-600 py-1 px-3 rounded-full text-xs">Voted</span>
                            @else
                                <span class="bg-purple-200 text-purple-600 py-1 px-3 rounded-full text-xs">Not Voted</span>
                            @endif
                        </td>

                        <td class="py-3 px-6 text-center">
                            <div class="flex item-center justify-center">
                                <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                    </svg>
                                </div>

                                <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                    <a href="{{ route('voter.edit', $voter) }}">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                        </svg>
                                    </a>
                                </div>

                                <div class="w-4 mr-2 transform hover:text-red-500 hover:scale-110">
                                    <form action="{{ route('voter.destroy', $voter) }}" method="POST" >
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" onclick="return confirm('Are you sure?')" class="w-4 h-4">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 1 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                    d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                            </svg>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </td>
                     </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>